#ifndef YI__CONSTANTS_H
#define YI__CONSTANTS_H

// IRC
#define YI_MAX_CHANNELS 15
#define YI_MAX_USERS 100
#define YI_MAX_USERS_PER_CHAN 15
#define YI_MAX_MESSAGE 513
#define YI_MAX_MESSAGE_PARAMS 15

// NET
#define YI_MAX_BACKLOG 10
#define YI_INET_ADDR_STRLEN 16
#define YI_INET6_ADDR_STRLEN 46

// GENERAL
#define YI_MAX_BUFFSIZE 8192
#define YI_MAX_LINE 4096
#define YI_MAX_NAME 255

#endif
